package com.seit.silaba.presentation.ws.model;

import java.util.Date;

import javax.faces.bean.ManagedProperty;

import com.seit.silaba.modelo.Tbsilaber;
import com.seit.silaba.presentation.businessDelegate.IBusinessDelegatorView;

/**
 * SilaberModel generated by wanferv
 */
public class SilaberModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer consecutivo;
	private String nombre;
	private String apellido;
	private String fechaNacimiento;
	private String telefonoFijo;
	private String telefonoCelular;
	private String fechaCreacion;
	private String usuarioCreacion;
	private String usuario;
	private String contrasena;
    @ManagedProperty(value = "#{BusinessDelegatorView}")
    private IBusinessDelegatorView businessDelegatorView;

	public SilaberModel() {
	}

	public SilaberModel(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	public  static SilaberModel setupModel (Tbsilaber  tbSilaber) {
		SilaberModel  model = new SilaberModel();
		model.setConsecutivo(tbSilaber.getConsecutivo());
		model.setNombre(tbSilaber.getNombre());
		model.setApellido(tbSilaber.getApellido());
		//model.setFechaNacimiento(tbSilaber.getFechaNacimiento());
		model.setTelefonoFijo(tbSilaber.getTelefonoFijo());
		model.setTelefonoCelular(tbSilaber.getTelefonoCelular());
		//model.setFechaCreacion(tbSilaber.getFechaCreacion());
		model.setUsuarioCreacion(tbSilaber.getUsuarioCreacion());
		model.setUsuario(tbSilaber.getUsuario());
		model.setContrasena(tbSilaber.getContrasena());
		return model;
	}
	public  static Tbsilaber convertToObject ( SilaberModel  model ) {
		Tbsilaber  tbSilaber = new Tbsilaber();
		
		tbSilaber.setConsecutivo(model.getConsecutivo());
		tbSilaber.setNombre(model.getNombre());
		tbSilaber.setApellido(model.getApellido());
		//tbSilaber.setFechaNacimiento(model.getFechaNacimiento());
		tbSilaber.setTelefonoFijo(model.getTelefonoFijo());
		tbSilaber.setTelefonoCelular(model.getTelefonoCelular());
		//tbSilaber.setFechaCreacion(model.getFechaCreacion());
		tbSilaber.setUsuarioCreacion(model.getUsuarioCreacion());
		tbSilaber.setUsuario(model.getUsuario());
		tbSilaber.setContrasena(model.getContrasena());
		return tbSilaber;
	}
	public Integer getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(String fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getTelefonoFijo() {
		return this.telefonoFijo;
	}

	public void setTelefonoFijo(String telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	public String getTelefonoCelular() {
		return this.telefonoCelular;
	}

	public void setTelefonoCelular(String telefonoCelular) {
		this.telefonoCelular = telefonoCelular;
	}

	public String getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(String fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasena() {
		return contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

}
